### ISSUE TITLE
Usage stats broken for Survival

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#124] opened 2013-06-09 07:45 UTC
By no means an immediate issue, but I figured i'd submit this anyway because it's a bug. You can see from each of the below links that Creative and PvE have had their usage stats updating fine and are as recent as June 8th, whereas Survival's appears to have stopped counting back on April 14th. Is there a clear reason as to why Survival's is the only one that hasn't been updating properly? There seems to be a bit of a worrying trend with things not working appropriately on Survival, hoping to get these things looked into.

http://nerd.nu/usage/creative/
http://nerd.nu/usage/pve/
http://nerd.nu/usage/survival/

**Comment by FourDown** [comment] 2013-06-09 13:30
There's another ticket from a few months ago open for similar issues to this.

https://github.com/NerdNu/NerdBugs/issues/20

**Comment by ethancedrik** [comment] 2013-07-12 06:56
Coolgamerovr90 here, It seems like recently C and P's usage stats have been updated, but Survival's still hasn't :(
Also the [Server] message saying "Track your addiction" is now gone, too

**Comment by LadyCailin** [comment] 2013-08-20 05:36
I'm currently working on this. I'm creating an all new format, which ties into the game with CH, and outputs the data with a PHP script. I'm doing limited testing atm, and we will see how efficient and how well this works. (It took like an hour to put together, so if it doesn't work, no huge loss.)

**Comment by LadyCailin** [comment] 2013-08-20 16:03
http://nerd.nu/usage/creative/index.php http://nerd.nu/usage/survival/index.php http://nerd.nu/usage/pve/index.php

Here's version 0.1, what do you guys think so far? I intend on adding the remaining data columns, and importing the old stats data, but other than that, it's fully functional so far.

**Comment by zifnab06** [comment] 2013-08-20 19:55
+1 from me. 

I believe the old list was sorted by 'days played' (being the number of days they logged in, not the total number of days since they begain playing).  Will that return?  (I only ask because it seems slightly more relevant - an alt of someone is currently the top on P and is online 24/7, a real person has no chance of beating that)

**Comment by LadyCailin** [comment] 2013-08-20 21:44
Ok, so after discussing it with @totemo and looking at the mountain of problems needed to reliably maintain (reliable being the keyword) historical data, we've decided not to import the old data at this time. We will reset per rev, but keep a copy of each rev's data on a static page, so that there can still be historical data, but it won't be "career" it would be per rev. The problem is that all ways of generating and maintaining data for 70,000+ users at once quickly becomes a nightmare, and is causing us to choose keeping that much data through complexity (and therefore unreliability) or trimming the data, allowing a simpler approach, and most likely higher reliability. We are still logging the raw data needed to calculate career data, through the form of archived console logs, but it's becoming too hard to maintain, hence it breaking relatively frequently. So anyways, if we decide that we want to do the work to get that working in the future we aren't preventing ourselves from doing so, but the amount of work to get that going right now just isn't worth it while we have other issues. (Any volunteers?)

I'm for closing this bug for now, because we have something that is perfectly workable for the time being, (and certainly an improvement from what it was) though if we decide to fix the historical stats, we can raise this issue again. I'll let discussion happen for a bit before I actually close the bug though.

Also, if you have any suggestions for the current pages, I think it's at "version 1.0 beta" now.

**Closed as completed** 2013-08-26 23:11 UTC
Labels: survival

**Comment by ethancedrik** [comment] 2013-08-27 23:25
I know this issue has been closed and I shouldn't really be commenting on it, but I have seen the usage stats randomly reset every so often, causing everyone's total play time to drop to 0. I'm not sure if you, @LadyCailin were working on it at the time and making changes to it, as that might explain the random reset, but if it does this every so often, it could cause some problems

**Comment by LadyCailin** [comment] 2013-08-27 23:38
I reset it a day or two ago, due to incompatible backed changes, I'm sure that's what you saw.
