### ISSUE TITLE
I'm running a 1.6 client and I can't connect to <server>.

### ISSUE THREAD

**Issue by nuclearstars** [NerdNu/NerdBugs#135] opened 2013-07-08 16:21 UTC
Protocol error 0xfa. This happened right after I somewhat fell off the world. Not fell out of the world like death, but I fell off a building, everything was super dark and I just kept falling.

**Comment by FourDown** [comment] 2013-07-08 17:29
You're on 1.6, you need to be on the super old 1.5.2 to be able to join nerd.nu servers.

The Protocol error 0xfa stuff is caused by a change to the way the client pings servers in 1.6.

EDIT: Thanks for updating the title, not sure what your issue is.

**Comment by LadyCailin** [comment] 2013-07-20 03:40
Well, we aren't running 1.6 yet, so.... Imma close this.

**Comment by totemo** [comment] 2013-07-21 15:13
Actually, the point of this bug (I edited the title) was just to act as a findable placeholder for the inevitable bugs about not being able to connect.  Reopening until people can no longer have the problem (i.e until we are on 1.6).

**Comment by totemo** [comment] 2013-08-15 08:46
And now all the servers are on 1.6 nobody needs to see this bug report any more.

**Closed as completed by totemo** 2013-08-15 08:46 UTC
